//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfCTSAdminModule.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/DBLibrary")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AunswerNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AunswerNum {
            get {
                return this.AunswerNumField;
            }
            set {
                if ((this.AunswerNumField.Equals(value) != true)) {
                    this.AunswerNumField = value;
                    this.RaisePropertyChanged("AunswerNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionTypeId {
            get {
                return this.QuestionTypeIdField;
            }
            set {
                if ((this.QuestionTypeIdField.Equals(value) != true)) {
                    this.QuestionTypeIdField = value;
                    this.RaisePropertyChanged("QuestionTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestId {
            get {
                return this.TestIdField;
            }
            set {
                if ((this.TestIdField.Equals(value) != true)) {
                    this.TestIdField = value;
                    this.RaisePropertyChanged("TestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceCTS")]
    public interface IServiceCTS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetSubjectsDataTable", ReplyAction="http://tempuri.org/IServiceCTS/GetSubjectsDataTableResponse")]
        System.Data.DataTable GetSubjectsDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetSubjectsDataTable", ReplyAction="http://tempuri.org/IServiceCTS/GetSubjectsDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSubjectsDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetTestsDataTableBySubjectId", ReplyAction="http://tempuri.org/IServiceCTS/GetTestsDataTableBySubjectIdResponse")]
        System.Data.DataTable GetTestsDataTableBySubjectId(int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetTestsDataTableBySubjectId", ReplyAction="http://tempuri.org/IServiceCTS/GetTestsDataTableBySubjectIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTestsDataTableBySubjectIdAsync(int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetQuestionsDataTableByTestId", ReplyAction="http://tempuri.org/IServiceCTS/GetQuestionsDataTableByTestIdResponse")]
        System.Data.DataTable GetQuestionsDataTableByTestId(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetQuestionsDataTableByTestId", ReplyAction="http://tempuri.org/IServiceCTS/GetQuestionsDataTableByTestIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetQuestionsDataTableByTestIdAsync(int testId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetQuestionById", ReplyAction="http://tempuri.org/IServiceCTS/GetQuestionByIdResponse")]
        wpfCTSAdminModule.ServiceReference1.Question GetQuestionById(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetQuestionById", ReplyAction="http://tempuri.org/IServiceCTS/GetQuestionByIdResponse")]
        System.Threading.Tasks.Task<wpfCTSAdminModule.ServiceReference1.Question> GetQuestionByIdAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetAnswersDataTableByQuestionId", ReplyAction="http://tempuri.org/IServiceCTS/GetAnswersDataTableByQuestionIdResponse")]
        System.Data.DataTable GetAnswersDataTableByQuestionId(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetAnswersDataTableByQuestionId", ReplyAction="http://tempuri.org/IServiceCTS/GetAnswersDataTableByQuestionIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAnswersDataTableByQuestionIdAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/DrawQuestionById", ReplyAction="http://tempuri.org/IServiceCTS/DrawQuestionByIdResponse")]
        string DrawQuestionById(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/DrawQuestionById", ReplyAction="http://tempuri.org/IServiceCTS/DrawQuestionByIdResponse")]
        System.Threading.Tasks.Task<string> DrawQuestionByIdAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/AuthenticateUser", ReplyAction="http://tempuri.org/IServiceCTS/AuthenticateUserResponse")]
        bool AuthenticateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/AuthenticateUser", ReplyAction="http://tempuri.org/IServiceCTS/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetUsersCount", ReplyAction="http://tempuri.org/IServiceCTS/GetUsersCountResponse")]
        int GetUsersCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetUsersCount", ReplyAction="http://tempuri.org/IServiceCTS/GetUsersCountResponse")]
        System.Threading.Tasks.Task<int> GetUsersCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetUsersDataTable", ReplyAction="http://tempuri.org/IServiceCTS/GetUsersDataTableResponse")]
        System.Data.DataTable GetUsersDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/GetUsersDataTable", ReplyAction="http://tempuri.org/IServiceCTS/GetUsersDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUsersDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/IIsLifeGood", ReplyAction="http://tempuri.org/IServiceCTS/IIsLifeGoodResponse")]
        bool IIsLifeGood();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/IIsLifeGood", ReplyAction="http://tempuri.org/IServiceCTS/IIsLifeGoodResponse")]
        System.Threading.Tasks.Task<bool> IIsLifeGoodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/addUserTest", ReplyAction="http://tempuri.org/IServiceCTS/addUserTestResponse")]
        void addUserTest(int id_user, int id_test, int numberOfTries, float mark, bool ifAvailable, System.DateTime testTime, bool canSkip, bool canBack, int testContinuesTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCTS/addUserTest", ReplyAction="http://tempuri.org/IServiceCTS/addUserTestResponse")]
        System.Threading.Tasks.Task addUserTestAsync(int id_user, int id_test, int numberOfTries, float mark, bool ifAvailable, System.DateTime testTime, bool canSkip, bool canBack, int testContinuesTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCTSChannel : wpfCTSAdminModule.ServiceReference1.IServiceCTS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCTSClient : System.ServiceModel.ClientBase<wpfCTSAdminModule.ServiceReference1.IServiceCTS>, wpfCTSAdminModule.ServiceReference1.IServiceCTS {
        
        public ServiceCTSClient() {
        }
        
        public ServiceCTSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCTSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCTSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCTSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetSubjectsDataTable() {
            return base.Channel.GetSubjectsDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSubjectsDataTableAsync() {
            return base.Channel.GetSubjectsDataTableAsync();
        }
        
        public System.Data.DataTable GetTestsDataTableBySubjectId(int subjectId) {
            return base.Channel.GetTestsDataTableBySubjectId(subjectId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTestsDataTableBySubjectIdAsync(int subjectId) {
            return base.Channel.GetTestsDataTableBySubjectIdAsync(subjectId);
        }
        
        public System.Data.DataTable GetQuestionsDataTableByTestId(int testId) {
            return base.Channel.GetQuestionsDataTableByTestId(testId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetQuestionsDataTableByTestIdAsync(int testId) {
            return base.Channel.GetQuestionsDataTableByTestIdAsync(testId);
        }
        
        public wpfCTSAdminModule.ServiceReference1.Question GetQuestionById(int questionId) {
            return base.Channel.GetQuestionById(questionId);
        }
        
        public System.Threading.Tasks.Task<wpfCTSAdminModule.ServiceReference1.Question> GetQuestionByIdAsync(int questionId) {
            return base.Channel.GetQuestionByIdAsync(questionId);
        }
        
        public System.Data.DataTable GetAnswersDataTableByQuestionId(int questionId) {
            return base.Channel.GetAnswersDataTableByQuestionId(questionId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAnswersDataTableByQuestionIdAsync(int questionId) {
            return base.Channel.GetAnswersDataTableByQuestionIdAsync(questionId);
        }
        
        public string DrawQuestionById(int questionId) {
            return base.Channel.DrawQuestionById(questionId);
        }
        
        public System.Threading.Tasks.Task<string> DrawQuestionByIdAsync(int questionId) {
            return base.Channel.DrawQuestionByIdAsync(questionId);
        }
        
        public bool AuthenticateUser(string username, string password) {
            return base.Channel.AuthenticateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password) {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public int GetUsersCount() {
            return base.Channel.GetUsersCount();
        }
        
        public System.Threading.Tasks.Task<int> GetUsersCountAsync() {
            return base.Channel.GetUsersCountAsync();
        }
        
        public System.Data.DataTable GetUsersDataTable() {
            return base.Channel.GetUsersDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUsersDataTableAsync() {
            return base.Channel.GetUsersDataTableAsync();
        }
        
        public bool IIsLifeGood() {
            return base.Channel.IIsLifeGood();
        }
        
        public System.Threading.Tasks.Task<bool> IIsLifeGoodAsync() {
            return base.Channel.IIsLifeGoodAsync();
        }
        
        public void addUserTest(int id_user, int id_test, int numberOfTries, float mark, bool ifAvailable, System.DateTime testTime, bool canSkip, bool canBack, int testContinuesTime) {
            base.Channel.addUserTest(id_user, id_test, numberOfTries, mark, ifAvailable, testTime, canSkip, canBack, testContinuesTime);
        }
        
        public System.Threading.Tasks.Task addUserTestAsync(int id_user, int id_test, int numberOfTries, float mark, bool ifAvailable, System.DateTime testTime, bool canSkip, bool canBack, int testContinuesTime) {
            return base.Channel.addUserTestAsync(id_user, id_test, numberOfTries, mark, ifAvailable, testTime, canSkip, canBack, testContinuesTime);
        }
    }
}
